version: '3'
services:
  app:
    # build = dockerイメージをビルドする時の設定
    build:
      context: .
      dockerfile: 'DEV.Dockerfile'
    container_name: docker-rails-service
    # command = コンテナ起動時にコンテナ内で実行するコマンド（railsのサービスなのでrailsの起動コマンドを実行）
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    # volumes = コンテナ内で発生したデータをコンテナの外部に永続化させるための設定（volumesは保存する箱みたいなもの）
    volumes:
      - .:/webapp:cached
      - bundle:/usr/local/bundle:cached
      - node_modules:/webapp/node_modules:cached
      - packs:/webapp/public/packs
    # ports = ホストPCのポート：コンテナポート（コンテナの3000ポートをホストPCの3000ポートにバインディング（繋げるみたいな意味）する。）
    ports:
      - "3000:3000"
    # depends_on = dbサービス（コンテナ）を起動した後にappサービス(コンテナ)を起動する（依存関係のこと）
    depends_on:
      - db
      - webpacker
    environment:
      WEBPACKER_DEV_SERVER_HOST: webpacker
    # (stdin_open,tty) = コンテナ内でデバックできるようにする
    stdin_open: true
    tty: true
  webpacker:
    build:
      context: .
      dockerfile: 'DEV.Dockerfile'
    volumes:
      - .:/webapp:cached
      - bundle:/usr/local/bundle:cached
      - node_modules:/webapp/node_modules:cached
      - packs:/webapp/public/packs
    command: bin/webpack-dev-server
    environment:
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    ports:
      - "3035:3035"
  db:
    image: mysql:8.0
    container_name: docker-db-service
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
  bundle:
  node_modules:
  packs:
